# Usa imagem oficial do Python
FROM python:3.10-slim

# Define Diretorio de trabalho dentro do container
WORKDIR /app

# Copia requirements primeiro (melhora cache)
COPY requirements.txt .

# instala dependencias
RUN pip install --no-cache-dir -r requirements

#Copiar  restantye do projeto
COPY . .

# Expoe a porta da aplicaçao
EXPOSE 8000

#Comando para rodar a API
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
